# Generated by Django 4.0 on 2022-01-22 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_barramenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barramenu',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='nombre'),
        ),
    ]
