# Generated by Django 4.0 on 2022-01-23 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_barramenu_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barramenu',
            options={'verbose_name': 'bara menu', 'verbose_name_plural': 'barra de menus'},
        ),
    ]
