# Generated by Django 4.0 on 2022-01-23 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_barramenu_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='barramenu',
            name='referencia',
            field=models.CharField(default='fix_menu', max_length=50),
            preserve_default=False,
        ),
    ]
