# Generated by Django 4.0 on 2022-03-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_barramenu_referencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitanos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje_llamado', models.CharField(max_length=100, verbose_name='mensaje de llamado')),
                ('submensaje_llamado', models.CharField(max_length=100, verbose_name='segundo mensaje de llama')),
                ('dias_laborable', models.CharField(max_length=50, verbose_name='dias de oficinas')),
                ('horario', models.CharField(max_length=10, verbose_name='horario')),
                ('horario_sabado', models.CharField(max_length=100, verbose_name='horario del sábado')),
                ('horario_domingo', models.CharField(max_length=100, verbose_name='horario domingo')),
                ('direccion', models.CharField(max_length=100, verbose_name='calle princilap')),
                ('pais_ciudad', models.CharField(max_length=100, verbose_name='ciudad pais')),
                ('llamada_accion', models.CharField(max_length=100, verbose_name='llamada a la acción')),
                ('telefofo', models.IntegerField(max_length=9, verbose_name='numero de telefono')),
                ('celular', models.IntegerField(max_length=9, verbose_name='numero celular')),
            ],
            options={
                'verbose_name': 'visita',
                'verbose_name_plural': 'visitanos',
            },
        ),
    ]
