# Generated by Django 4.0 on 2022-03-04 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_visitanos_celular_alter_visitanos_telefofo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Visitanos',
            new_name='Visita',
        ),
        migrations.AlterModelOptions(
            name='visita',
            options={'verbose_name': 'visita', 'verbose_name_plural': 'visitas'},
        ),
    ]
