# Generated by Django 4.0 on 2022-03-14 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_visitanos_visita_alter_visita_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='celular',
            field=models.CharField(max_length=10, verbose_name='numero celular'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='telefofo',
            field=models.CharField(max_length=9, verbose_name='numero de telefono'),
        ),
    ]
