# Generated by Django 4.0 on 2022-03-15 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_visita_celular_alter_visita_telefofo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='titulo')),
                ('subtitle', models.CharField(max_length=100, verbose_name='subtitulo')),
                ('contenido', models.TextField(max_length=300, verbose_name='historia')),
                ('image', models.ImageField(upload_to='', verbose_name='imagen')),
            ],
            options={
                'verbose_name': 'historia',
                'verbose_name_plural': 'historias',
            },
        ),
    ]
