# Generated by Django 4.0 on 2022-01-15 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=100, unique=True, verbose_name='nombre de clave')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('url', models.URLField(blank=True, null=True, verbose_name='link')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='fecha de actualizació')),
            ],
            options={
                'verbose_name': 'red social',
                'verbose_name_plural': 'redes sociales',
                'ordering': ['-created'],
            },
        ),
    ]
