# Generated by Django 4.0 on 2022-01-15 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Social',
            new_name='Link',
        ),
    ]
