# Generated by Django 4.0 on 2022-03-08 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='columnaalquiler',
            old_name='precio',
            new_name='pre',
        ),
    ]
