# Generated by Django 4.0 on 2022-03-15 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_plano'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gypsum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='titulo')),
                ('pre', models.CharField(max_length=10, verbose_name='precio')),
                ('content', models.TextField(verbose_name='contenido')),
                ('image', models.ImageField(upload_to='servicios', verbose_name='imagen')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='fecha de actualizació')),
            ],
            options={
                'verbose_name': 'gypsum',
                'verbose_name_plural': 'gypsums',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Losa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='titulo')),
                ('pre', models.CharField(max_length=10, verbose_name='precio')),
                ('content', models.TextField(verbose_name='contenido')),
                ('image', models.ImageField(upload_to='servicios', verbose_name='imagen')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='fecha de actualizació')),
            ],
            options={
                'verbose_name': 'losa',
                'verbose_name_plural': 'losas',
                'ordering': ['-created'],
            },
        ),
    ]
